### ISSUE TITLE
Onde se organizar?

### ISSUE THREAD

**Issue by nellfs** [Autistalive/web#9]
Desculpem se aqui não é o local certo para falar sobre isso, mas acho que essa issue vai interessar outras pessoas que querem colaborar com o projeto.

* Qual seria o melhor local para se organizar e conversar sobre o projeto? 

Um local para os colaboradores conseguirem debater ideias juntos antes de tomar decisões, ou para informar do progresso de algum PR. Existe algum servidor IRC ou Matrix para isso? Se sim, por favor adicionem ao [READ.ME](https://github.com/Autistalive/web/blob/main/README.md) do projeto ❤️

**Comment by slackjeff** [comment]
Salve, temos servidor irc e xmpp pode ser via irc pois não precisa de cadastro, vou por no readme e criar uma sala

**Comment by nellfs** [comment]
Ótimo! Quando adicionar o servidor IRC e o XMPP responde por aqui também, vou fechar a issue quando conseguir entrar na sala. :)

**Comment by slackjeff** [comment]
Aqui:
autista.live@conference.slackjeff.com.br

Se você estiver usando Linux, você pode usar os seguintes clientes: Gajim, Dino, ou via web Converse.js

**Comment by nellfs** [comment]
Valeu! Vi que foi [atualizado no READ.ME](https://github.com/Autistalive/web/commit/d4669c9cf4691fc1cbd74dd256e99fdbe145558c) também. Fechando a issue aqui!! 🩵
